### ISSUE TITLE
Existing user files not transferred to new IDE

### ISSUE THREAD

**Issue by MadDogDean** [cs50/v4-issues#1]
![cs50 ide](https://user-images.githubusercontent.com/23712335/51362006-d6464e00-1b0c-11e9-9a97-92daac0ba50a.jpg)
#### What symptom did you see (attaching screenshots as necessary)?
User "workspace" directory not showing
User files not transferred to new IDE
#### When date and time (UTC) did the problem happen?
Jan 18, 2:25 UTC
#### What steps did you follow to reproduce the problem?
When logging in to the beta IDE for the first time, I expected my existing user files would have been transferred as well. There was no *workspace* fol;der and no user files. I tried to cd to *workspace* but folder is not found.
I returned to the legacy ide and all files are shown and accounted for.
The same GitHub login  is used for both ide's.

#### Which web browser did you use (including version number)?
FireFox 63.0.3
#### Which operating system did you use (including version number)?
Windows 7 x64, 6.1 build 7601
#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
Yes

**Comment by kzidane** [comment]
Thanks for giving it a try, @MadDogDean! This is an expected behavior though. We're not (yet) migrating data automatically from legacy. It should be fairly easy for you to do that though if you want:

1. In legacy, click File > Download Project to download a zip of your `~/workspace` folder. 
2. In beta click File > Upload Local Files ... > Select Files.
3. Navigate your way to where you downloaded the zip on your computer and select it.
4. After the zip is uploaded to you, run `unzip FILENAME` in a terminal tab, where `FILENAME` is the name of the zip file, to extract your files in the new workspace.

Let us know if you need further help!

**Comment by MadDogDean** [comment]
No trouble Kareem, just wanting to do my part :)
Cheers
