### ISSUE TITLE
Wrong URL opening when trying to open server

### ISSUE THREAD

**Issue by iUtsavB** [cs50/v4-issues#12]
#### What symptom did you see (attaching screenshots as necessary)?
![image](https://user-images.githubusercontent.com/14871819/55439154-55eaa180-55c1-11e9-8641-26c072c349c2.png)
#### When date and time (UTC) did the problem happen?
03/04/2019 03:34 UTC+5:30
#### What steps did you follow to reproduce the problem?
1. step 1. logged in to ide
1. step 2. open server by clicking on CS50 IDE -> Web Server
1. step 3. new tab opens and https://us-east-1.console.aws.amazon.com/cloud9/ide/ec2-18-207-133-67.compute-1.amazonaws.com  URL opens

#### Which web browser did you use (including version number)?
Google Chrome Version 73.0.3683.86 (Official Build) (64-bit)
#### Which operating system did you use (including version number)?
Windows 10 Pro Build 1809
#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
Yes

**Comment by nathswastik** [comment]
Same happens when I try to do so. One solution which found is taking the url after https://us-east-1.console.aws.amazon.com/cloud9/ide/ and opening it as "https://ec2-18-207-133-67.compute-1.amazonaws.com".

P.S: Hope this issue will be fixed soon. It is quite cumbersome to click the Web Server and then copy a part of the link and open it in a new tab.

**Comment by kzidane** [comment]
Thanks for reporting this! This issue should be fixed now.
