### ISSUE TITLE
Manually installed application are gone after logging out of ide

### ISSUE THREAD

**Issue by SNathJr** [cs50/v4-issues#14]
#### What symptom did you see (attaching screenshots as necessary)?

Any manually installed application (using apt-get) uninstalls after logging out of CS50 ide.

#### When date and time (UTC) did the problem happen?

9:23 am
Sunday, 14 April 2019
Coordinated Universal Time (UTC)

#### What steps did you follow to reproduce the problem?
1. step 1
install any application through apt-get

```
$ sudo apt-get update
$ sudo apt-get install screen
```
2. step 2
Check that newly installed software is actually installed
```
$ screen -v
Screen version 4.06.02 (GNU) 23-Oct-17
```
3. step 3
Log out of CS50 ide and log back in

4. step 4
check for previously installed application
```
$ screen
bash: screen: command not found
```

#### Which web browser did you use (including version number)?

Chrome (latest)
Firefox (latest)
Microsoft Edge

#### Which operating system did you use (including version number)?

Windows 10 Version 1809

#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?

Yes, user name: SNathJr

**Comment by kzidane** [comment]
Hi @SNathJr,

Thank you for using CS50 IDE beta! It is by design that only your home folder (`/home/ubuntu`) persists across different sessions in the beta IDE. The main motivation behind this decision is being able to easily provide managed updates (i.e., update your IDE automatically) without having you manually run a command like `update50` that basically resets and updates the environment. 

Using a tool like `update50` wasn't ideal because it used to take so long to run and it was difficult to maintain since many students' IDEs drifted out of date all the time and some students would install or configure packages in their IDEs that would break or conflict with our updating tool or break their IDEs after the update which wasn't ideal.

Given that the IDE is primarily meant to be used for CS50 and other courses, we thought just persisting the user's home folder is perhaps the best approach for us moving forward but we welcome feature requests to install packages that are not already installed in case there's a reasonable use case for them in the context of CS50 or other courses.

Alternatively, even though perhaps not ideal, you may want to write a simple bash script that installs and configures your packages the way you want and run that script every time you start a new session in the IDE. Hope that helps!

**Comment by SNathJr** [comment]
Hi @kzidane 

I am taking the CS50 Web Programming with Python and Javascript course (CS50w). Many of the tools/applications needed in that course does not come pre-installed in the newest CS50 ide. `psql` and `heroku` to name a few. However, installing them every time I log back into my IDE has become a pain in the neck.

If there is a way in which I can make my application install persistent, it would be very helpful. Also, thank you for taking time to reply.

Sincerely,
SNathJr

**Comment by kzidane** [comment]
@SNathJr we've started rolling out updates that include `heroku` and `psql` in the IDE. Thanks!

**Comment by SNathJr** [comment]
@kzidane Impeccable! Thank you very much.
