### ISSUE TITLE
Preview of HTML appears/disappears from context menu

### ISSUE THREAD

**Issue by stephendgilbert** [cs50/v4-issues#18]
#### What symptom did you see (attaching screenshots as necessary)?
When I right-click an HTML file in the file tree, I am given the option to open, display as HTML, serve it (grayed out), download or preview it. Clicking preview displays the file correctly in a tab. One I have clicked on one file, however, the Preview option disappears from the context menu.
Pictures below: 
1. right-clicking preview, 
![image](https://user-images.githubusercontent.com/15840496/57485038-8c21dd80-725f-11e9-89a1-f2b9fff90f83.png)

2. after previewing the file
![image](https://user-images.githubusercontent.com/15840496/57485084-9e038080-725f-11e9-9790-dab31f207bc4.png)

#### When date and time (UTC) did the problem happen?
Thu May  9 20:31:23 UTC 2019

#### What steps did you follow to reproduce the problem?
1. Place an html file in the workspace
2. Right-click and preview it. Works ok (displays the web page)
3. Right-click again (on any HTML file) and Preview has disappeared
4. Reload the page and Preview appears again (for one time). 

#### Which web browser did you use (including version number)?
Google Chrome Version 74.0.3729.131 (Official Build) (64-bit)

#### Which operating system did you use (including version number)?
Windows 7 Enterprise Service Pack 1

#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
I believe I did although all information seems to be stripped out once I'm logged into the CS50 ide, so it's kind of hard to tell. In the old CS50 ide I could look at the environment to see.

**Comment by kzidane** [comment]
Preview showing up at times is likely a bug that I'm going to fix as soon
as possible. The Serve option is available for folders only. So if you
right-click on the parent folder for example you should be about to serve
it.


Kareem

**Comment by bmuellerhstat** [comment]
@kzidane you say that *Preview* showing up is a bug, but can that feature stay in the cs50 IDE permanently? It would be nice to preview HTML without having to always `http-serve`, and even better, it can be used to preview markdown files, which I can't figure out how to otherwise serve.

**Comment by bmuellerhstat** [comment]
@kzidane any updates on this?

**Comment by bmuellerhstat** [comment]
@kzidane should we still use this repo for issues, or email sysadmins@cs50.harvard.edu with any ongoing problems?

**Comment by kzidane** [comment]
Either is fine. Thanks!


Kareem

**Comment by bmuellerhstat** [comment]
Great, thanks @kzidane ! Any updates about my comment from 5/12?

**Comment by kzidane** [comment]
Still looking into that @bmuellerhstat, sorry! I'll get back to you asap.

**Comment by bmuellerhstat** [comment]
Thanks @kzidane - any updates about the preview button in the menu?

**Comment by kzidane** [comment]
This issue should be fixed now.

**Comment by Abhigya3159** [comment]
I made a directory called readability and opened a file readbility.c in it. I accidentally deleted the file. Since I had not coded much, I just decided to open a new file of the same name. However, when I type in the command 'open readability.c,' the same deleted file opens up but it does not show up in the file tree. And I am unable to compile it because the file does not actually exist in the readability directory. Is there a way I can start the pset2 Readability afresh? I tried by deleting the directory. But when I made the directory once again and tried to open the readability.c file in it, the same deleted file is opened 
![20200428_162435](https://user-images.githubusercontent.com/64054535/80479808-39a86800-896d-11ea-8a95-10230f97dec0.jpg)
up.
